import { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { WorkflowNotifications, type WorkflowNotification } from '../../lib/workflowNotifications';
import { Target, CheckCircle, Rocket, Clock, TrendingUp, AlertCircle } from 'lucide-react';
import { getModalZIndexClass, getModalBackdropZIndexClass } from '../../lib/zIndex';

interface SettingsModalProps {
  isOpen: boolean;
  onClose: () => void;
}

interface Notification {
  id: number | string;
  text: string;
  title?: string;
  timestamp: string;
  read: boolean;
  sourceId: string;
  createdAt: number;
  type?: string;
  actionUrl?: string;
  actionText?: string;
  priority?: 'high' | 'medium' | 'low';
  isWorkflow?: boolean;
}

export default function NotificationModal({ isOpen, onClose }: SettingsModalProps) {
  const [isHistoryView, setIsHistoryView] = useState(false);
  const [notifications, setNotifications] = useState<Notification[]>([
    // Today
    { id: 1, text: "Your profile analysis is complete. View your new insights.", timestamp: "5 mins ago", read: false, sourceId: 'brand-intelligence', createdAt: new Date('2025-09-20T09:35:00Z').getTime() },
    { id: 2, text: "Your brand score improved by 5 points!", timestamp: "50 mins ago", read: false, sourceId: 'brand-audit', createdAt: new Date('2025-09-20T08:50:00Z').getTime() },
    { id: 3, text: "New feature 'AI Portfolio' is now available.", timestamp: "2 hours ago", read: false, sourceId: 'career-portfolio', createdAt: new Date('2025-09-20T07:50:00Z').getTime() },
    { id: 4, text: "You have 3 new job recommendations.", timestamp: "5 hours ago", read: false, sourceId: 'job-finder', createdAt: new Date('2025-09-20T04:50:00Z').getTime() },
    // Yesterday
    { id: 5, text: "You have a new connection request from Jane Doe.", timestamp: "Yesterday", read: true, sourceId: 'event-scout', createdAt: new Date('2025-09-19T18:00:00Z').getTime() },
    { id: 6, text: "Monthly Brand Review is ready.", timestamp: "Yesterday", read: true, sourceId: 'brand-audit', createdAt: new Date('2025-09-19T12:00:00Z').getTime() },
    // This Week
    { id: 7, text: "A new post was generated for your review.", timestamp: "Wednesday", read: true, sourceId: 'content-engine', createdAt: new Date('2025-09-17T10:00:00Z').getTime() },
    { id: 8, text: "3 new articles have been generated by the Content Engine.", timestamp: "Tuesday", read: true, sourceId: 'content-engine', createdAt: new Date('2025-09-16T14:00:00Z').getTime() },
    // Previously (This Month / Older)
    { id: 9, text: "A new skill 'Data Analysis' was added to your Skill Radar.", timestamp: "Sep 5", read: true, sourceId: 'skill-radar', createdAt: new Date('2025-09-05T09:00:00Z').getTime() },
    { id: 10, text: "Your 'Content Engine' summary from last month.", timestamp: "Last month", read: true, sourceId: 'content-engine', createdAt: new Date('2025-08-15T12:00:00Z').getTime() },
    { id: 11, text: "Older notification from a while back.", timestamp: "2 months ago", read: true, sourceId: 'dashboard', createdAt: new Date('2025-07-10T12:00:00Z').getTime() },
  ]);
  const [notificationHistory, setNotificationHistory] = useState<Notification[]>([]);
  const navigate = useNavigate();

  // Load and merge workflow notifications
  useEffect(() => {
    if (isOpen) {
      // Check for new workflow notifications
      const newWorkflowNotifications = WorkflowNotifications.checkAndGenerate();
      
      // Load existing workflow notifications
      const workflowNotifications = WorkflowNotifications.getNotifications();
      
      // Check for persistent notifications (important ones that should be shown)
      const persistentNotifications = WorkflowNotifications.getPersistentNotifications();
      
      // Convert workflow notifications to regular notification format
      const convertedWorkflowNotifications: Notification[] = workflowNotifications.map(wfNotif => ({
        id: wfNotif.id,
        text: wfNotif.message,
        title: wfNotif.title,
        timestamp: formatTimestamp(wfNotif.timestamp),
        read: wfNotif.read,
        sourceId: `workflow-${wfNotif.workflowId}`,
        createdAt: wfNotif.timestamp,
        type: wfNotif.type,
        actionUrl: wfNotif.actionUrl,
        actionText: wfNotif.actionText,
        priority: wfNotif.priority,
        isWorkflow: true
      }));

      // Merge with existing notifications, avoiding duplicates
      setNotifications(prev => {
        const existingIds = new Set(prev.map(n => n.id));
        const newOnes = convertedWorkflowNotifications.filter(n => !existingIds.has(n.id));
        return [...prev, ...newOnes].sort((a, b) => b.createdAt - a.createdAt);
      });
    }
  }, [isOpen]);

  // Format timestamp helper
  const formatTimestamp = (timestamp: number): string => {
    const now = Date.now();
    const diff = now - timestamp;
    const minutes = Math.floor(diff / 60000);
    const hours = Math.floor(diff / 3600000);
    const days = Math.floor(diff / 86400000);

    if (minutes < 1) return 'Just now';
    if (minutes < 60) return `${minutes} min${minutes !== 1 ? 's' : ''} ago`;
    if (hours < 24) return `${hours} hour${hours !== 1 ? 's' : ''} ago`;
    if (days < 7) return `${days} day${days !== 1 ? 's' : ''} ago`;
    return new Date(timestamp).toLocaleDateString('en-US', { month: 'short', day: 'numeric' });
  };

  // Filter old notifications (older than 30 days) and load workflow notifications
  useEffect(() => {
    const thirtyDaysAgo = Date.now() - (30 * 24 * 60 * 60 * 1000);
    setNotifications(prev => prev.filter(n => n.createdAt >= thirtyDaysAgo));
    
    // Load workflow notifications when modal opens
    if (isOpen) {
      const workflowNotifications = WorkflowNotifications.getNotifications();
      const convertedWorkflowNotifications: Notification[] = workflowNotifications.map(wfNotif => ({
        id: wfNotif.id,
        text: wfNotif.message,
        title: wfNotif.title,
        timestamp: formatTimestamp(wfNotif.timestamp),
        read: wfNotif.read,
        sourceId: `workflow-${wfNotif.workflowId}`,
        createdAt: wfNotif.timestamp,
        type: wfNotif.type,
        actionUrl: wfNotif.actionUrl,
        actionText: wfNotif.actionText,
        priority: wfNotif.priority,
        isWorkflow: true
      }));

      setNotifications(prev => {
        const existingIds = new Set(prev.map(n => n.id));
        const newOnes = convertedWorkflowNotifications.filter(n => !existingIds.has(n.id));
        return [...prev, ...newOnes].sort((a, b) => b.createdAt - a.createdAt);
      });
    }
  }, [isOpen]);

  const getNotificationCategory = (timestamp: number): string => {
    const now = new Date('2025-09-20T09:10:00'); // Fixed time for consistent demo
    const date = new Date(timestamp);
    
    const today = new Date(now.getFullYear(), now.getMonth(), now.getDate());
    const yesterday = new Date(today);
    yesterday.setDate(yesterday.getDate() - 1);
    const notificationDate = new Date(date.getFullYear(), date.getMonth(), date.getDate());
    
    if (notificationDate.getTime() === today.getTime()) return 'Today';
    if (notificationDate.getTime() === yesterday.getTime()) return 'Yesterday';
    
    const startOfWeek = new Date(today);
    startOfWeek.setDate(today.getDate() - today.getDay());
    if (notificationDate >= startOfWeek) return 'This Week';
    
    const startOfMonth = new Date(today.getFullYear(), today.getMonth(), 1);
    if (notificationDate >= startOfMonth) return 'This Month';
    
    return 'Older';
  };

  const handleNotificationClick = (notification: Notification) => {
    if (isHistoryView) return;

    // Mark as read if unread
    if (!notification.read) {
      setNotifications(prev =>
        prev.map(n => n.id === notification.id ? { ...n, read: true } : n)
      );
      
      // Mark workflow notification as read if it's a workflow notification
      if (notification.isWorkflow && typeof notification.id === 'string') {
        WorkflowNotifications.markAsRead(notification.id);
      }
    }

    // Handle workflow notifications
    if (notification.isWorkflow && notification.actionUrl) {
      navigate(notification.actionUrl);
      onClose();
      return;
    }

    // Navigate to the source page
    const routeMap: Record<string, string> = {
      'brand-audit': '/dashboard/brand-audit',
      'brand-intelligence': '/dashboard/brand-audit',
      'career-portfolio': '/dashboard/portfolio',
      'job-finder': '/dashboard/job-finder',
      'event-scout': '/dashboard/event-scout',
      'content-engine': '/dashboard/content-engine',
      'skill-radar': '/dashboard/skill-radar',
      'dashboard': '/dashboard',
    };

    const route = notification.actionUrl || routeMap[notification.sourceId];
    if (route) {
      navigate(route);
      onClose();
    }
  };

  const handleClearAll = () => {
    setNotificationHistory(prev => [...prev, ...notifications]);
    setNotifications([]);
  };

  const unreadCount = notifications.filter(n => !n.read).length;
  const listToRender = isHistoryView ? notificationHistory : notifications;

  // Group notifications by category
  const grouped = listToRender.reduce((acc, n) => {
    const category = getNotificationCategory(n.createdAt);
    if (!acc[category]) acc[category] = [];
    acc[category].push(n);
    return acc;
  }, {} as Record<string, Notification[]>);

  const categoryOrder = ['Today', 'Yesterday', 'This Week', 'This Month', 'Older'];

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center">
      {/* Overlay */}
      <div 
        className="absolute inset-0 bg-black/50 backdrop-blur-sm"
        onClick={onClose}
      />

      {/* Modal Content */}
      <div className="relative w-full max-w-2xl bg-white/80 dark:bg-slate-800/80 backdrop-blur-xl rounded-2xl shadow-lg border border-white/30 dark:border-slate-700 m-4 flex flex-col" style={{ maxHeight: '90vh' }}>
        {/* Header */}
        <div className="flex items-center justify-between p-5 flex-shrink-0">
          <div className="flex items-center gap-3">
            <h3 className="text-lg font-semibold text-slate-900 dark:text-white">
              {isHistoryView ? 'History' : 'Notifications'}
            </h3>
            {!isHistoryView && unreadCount > 0 && (
              <span className="bg-slate-600 text-white text-xs font-semibold px-2 py-0.5 rounded-full">
                {unreadCount > 99 ? '99+' : unreadCount}
              </span>
            )}
          </div>
          <button
            onClick={onClose}
            className="p-2 rounded-lg hover:bg-slate-200/60 dark:hover:bg-slate-700 text-slate-500 dark:text-slate-400"
          >
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="w-6 h-6">
              <line x1="18" y1="6" x2="6" y2="18"></line>
              <line x1="6" y1="6" x2="18" y2="18"></line>
            </svg>
          </button>
        </div>

        {/* Notification List */}
        <ul className="overflow-y-auto p-4 space-y-3 flex-grow custom-scrollbar relative">
          {listToRender.length === 0 ? (
            <li className="text-center text-slate-600 dark:text-slate-400 py-12">
              {isHistoryView ? "Your notification history is empty." : "You're all caught up!"}
            </li>
          ) : (
            categoryOrder.map(category => {
              if (!grouped[category]) return null;
              
              return (
                <div key={category}>
                  <li className="notification-category-header">
                    <h4 className="text-sm font-bold text-slate-600 dark:text-slate-400 py-2">
                      {category}
                    </h4>
                  </li>
                  {grouped[category].map(notification => {
                    let displayTimestamp = notification.timestamp;
                    if (['This Week', 'This Month', 'Older'].includes(category)) {
                      const date = new Date(notification.createdAt);
                      displayTimestamp = date.toLocaleDateString('en-US', { month: 'short', day: 'numeric' });
                    }

                    return (
                      <li
                        key={notification.id}
                        onClick={() => handleNotificationClick(notification)}
                        className={`flex items-start gap-4 p-4 rounded-xl transition-colors ${
                          !isHistoryView && !notification.read
                            ? 'cursor-pointer bg-slate-50 dark:bg-slate-800/50 border border-slate-200 dark:border-slate-700 hover:bg-slate-100 dark:hover:bg-slate-700'
                            : 'bg-slate-50/50 dark:bg-slate-800/50 hover:bg-slate-100 dark:hover:bg-slate-700'
                        }`}
                      >
                        <div className={`flex-shrink-0 w-12 h-12 rounded-full flex items-center justify-center shadow-md ${
                          notification.isWorkflow 
                            ? notification.type === 'workflow-completed' ? 'bg-green-100 dark:bg-green-900/30' :
                              notification.type === 'step-completed' ? 'bg-blue-100 dark:bg-blue-900/30' :
                              notification.type === 'workflow-started' ? 'bg-purple-100 dark:bg-purple-900/30' :
                              notification.type === 'milestone' ? 'bg-amber-100 dark:bg-amber-900/30' :
                              notification.type === 'step-started-reminder' || notification.type === 'contextual-reminder' ? 'bg-slate-100 dark:bg-slate-900/30' :
                              'bg-slate-100 dark:bg-slate-900/30'
                            : 'bg-white dark:bg-slate-700'
                        }`}>
                          {notification.isWorkflow ? (
                            notification.type === 'workflow-completed' ? <CheckCircle className="w-5 h-5 text-green-600 dark:text-green-400" /> :
                            notification.type === 'step-completed' ? <CheckCircle className="w-5 h-5 text-blue-600 dark:text-blue-400" /> :
                            notification.type === 'workflow-started' ? <Rocket className="w-5 h-5 text-purple-600 dark:text-purple-400" /> :
                            notification.type === 'milestone' ? <TrendingUp className="w-5 h-5 text-amber-600 dark:text-amber-400" /> :
                            notification.type === 'inactivity' ? <Clock className="w-5 h-5 text-orange-600 dark:text-orange-400" /> :
                            notification.type === 'step-started-reminder' || notification.type === 'contextual-reminder' ? <Clock className="w-5 h-5 text-slate-600 dark:text-slate-400" /> :
                            <Target className="w-5 h-5 text-slate-600 dark:text-slate-400" />
                          ) : (
                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="w-5 h-5 text-slate-600">
                              <circle cx="12" cy="12" r="10"></circle>
                              <line x1="12" y1="16" x2="12" y2="12"></line>
                              <line x1="12" y1="8" x2="12.01" y2="8"></line>
                            </svg>
                          )}
                        </div>
                        <div className="flex-grow">
                          <div className="flex items-start justify-between">
                            <div className="flex-1 pr-2">
                              {notification.title && (
                                <p className="text-sm font-bold text-slate-900 dark:text-white mb-1">
                                  {notification.title}
                                </p>
                              )}
                              <p className={`text-sm ${notification.title ? 'text-slate-600 dark:text-slate-400' : 'font-medium text-slate-900 dark:text-white'}`}>
                                {notification.text}
                              </p>
                              {notification.isWorkflow && notification.actionText && (
                                <button
                                  onClick={(e) => {
                                    e.stopPropagation();
                                    if (notification.actionUrl) {
                                      navigate(notification.actionUrl);
                                      onClose();
                                    }
                                  }}
                                  className="mt-2 text-xs font-semibold text-slate-600 dark:text-slate-400 hover:text-slate-700 dark:hover:text-slate-300 flex items-center gap-1"
                                >
                                  {notification.actionText}
                                  <svg xmlns="http://www.w3.org/2000/svg" width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                                    <path d="M5 12h14M12 5l7 7-7 7"/>
                                  </svg>
                                </button>
                              )}
                            </div>
                            {!isHistoryView && !notification.read && (
                              <span className={`flex-shrink-0 text-xs font-medium px-2 py-1 rounded-full ${
                                notification.isWorkflow && notification.priority === 'high'
                                  ? 'bg-red-600 text-white'
                                  : notification.isWorkflow && notification.priority === 'medium'
                                  ? 'bg-amber-600 text-white'
                                  : 'bg-slate-600 text-white'
                              }`}>
                                New
                              </span>
                            )}
                          </div>
                          <p className="text-xs mt-1">
                            <span className="font-medium" style={{ color: '#111827' }}>
                              {displayTimestamp}
                            </span>
                            {notification.isWorkflow && notification.priority && (
                              <span className={`ml-2 text-xs px-2 py-0.5 rounded-full ${
                                notification.priority === 'high' ? 'bg-red-100 text-red-700 dark:bg-red-900/30 dark:text-red-400' :
                                notification.priority === 'medium' ? 'bg-amber-100 text-amber-700 dark:bg-amber-900/30 dark:text-amber-400' :
                                'bg-blue-100 text-blue-700 dark:bg-blue-900/30 dark:text-blue-400'
                              }`}>
                                {notification.priority}
                              </span>
                            )}
                          </p>
                        </div>
                      </li>
                    );
                  })}
                </div>
              );
            })
          )}
        </ul>

        {/* Footer Actions */}
        <div className="p-4 flex-shrink-0 flex items-center justify-between border-t border-white/30 dark:border-slate-700">
          {!isHistoryView ? (
            <>
              <button
                onClick={() => setIsHistoryView(true)}
                className="px-4 py-2 bg-slate-600/70 hover:bg-slate-600 text-white rounded-lg font-medium transition-all duration-300"
              >
                History
              </button>
              <button
                onClick={handleClearAll}
                className="px-4 py-2 bg-slate-600 text-white rounded-lg font-medium hover:bg-slate-700 transition-all duration-300"
              >
                Clear All
              </button>
            </>
          ) : (
            <button
              onClick={() => setIsHistoryView(false)}
              className="px-4 py-2 bg-slate-500 text-white rounded-lg font-medium hover:bg-slate-600 transition-all duration-300"
            >
              ← Back to Notifications
            </button>
          )}
        </div>
      </div>
    </div>
  );
}

